export const GET_CATALOG_PRODUCTS = "GET_CATALOG_PRODUCTS";
export const GET_CATALOG_PRODUCTS_SUCCESS = "GET_CATALOG_PRODUCTS_SUCCESS";
export const GET_CATALOG_PRODUCTS_FAILED = "GET_CATALOG_PRODUCTS_FAILED";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_FILTER = "SET_FILTER";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";