export const GET_CATALOG_PRODUCTS = "GET_CATALOG_PRODUCTS";
export const GET_CATALOG_PRODUCTS_SUCCESS = "GET_CATALOG_PRODUCTS_SUCCESS";
export const GET_CATALOG_PRODUCTS_FAILED = "GET_CATALOG_PRODUCTS_FAILED";